//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcassinLightDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id_Message { get; set; }
        public string Contenu { get; set; }
        public int id_source { get; set; }
        public int id_Room { get; set; }
        public byte[] date_ajout { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
