//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcassinLightDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarcassinEntities : DbContext
    {
        public MarcassinEntities()
            : base("name=MarcassinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Badge> Badge { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Categorie_Langue> Categorie_Langue { get; set; }
        public virtual DbSet<Competence> Competence { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Langue> Langue { get; set; }
        public virtual DbSet<Langue_Badge> Langue_Badge { get; set; }
        public virtual DbSet<Langue_Competence> Langue_Competence { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Utilisateur_Competence> Utilisateur_Competence { get; set; }
    }
}
