//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcassinLightDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur_Competence
    {
        public int id_Utilisateur { get; set; }
        public int id_Competence { get; set; }
        public int note { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
